import { Product, Review, Language } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'gur-thekua',
    name: 'Gur & Saunf Thekua',
    translationKey: 'gur_thekua',
    category: 'thekua',
    description: 'An aromatic cookie made with premium whole wheat, organic desi jaggery, crushed fennel seeds, and baked slowly in wood-fired earthen ovens.',
    story: 'Prepared exactly as our Grandmothers made back in the village (Ghar-Ghar ki Kahani) using hand-carved wooden moulds called "Sancha", leaving a beautiful leaf print.',
    price: 189,
    rating: 4.9,
    reviewCount: 342,
    unit: 'Pack of 350g',
    images: [
      'https://images.unsplash.com/photo-1600431521340-491eca880813?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1605001011156-cbf0b0f67a51?auto=format&fit=crop&w=600&q=80'
    ],
    ingredients: ['Sehore Whole Wheat Flour', 'Organic sugarcane Jaggery (Gur)', 'Cold-pressed Mustard Oil', 'Green Fennel Seeds (Saunf)', 'Water'],
    shelfLife: '45 Days (Store in cool, dry container)',
    nutrition: {
      calories: 420,
      protein: '6.4g',
      carbs: '68.5g',
      fat: '13.2g'
    },
    badges: ['Pure Jaggery', 'Wooden Sancha', 'Chhath Special Recipe', 'Soft Crunchy'],
    isBestSeller: true
  },
  {
    id: 'desi-ghee-thekua',
    name: 'Sancha Desi Ghee Thekua',
    translationKey: 'desi_ghee_thekua',
    category: 'thekua',
    description: 'Rich, melt-in-mouth traditional biscuit rich in A2 Desi Ghee and sweetened with organic sulphurless sugar. Indulgent, authentic, and golden.',
    story: 'Kneaded strictly by hand with generous dollops of warm Desi Ghee. The rich, buttery crackling texture is a heritage recipe preserved across five generations.',
    price: 249,
    rating: 5.0,
    reviewCount: 418,
    unit: 'Pack of 350g',
    images: [
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1605001011156-cbf0b0f67a51?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=600&q=80'
    ],
    ingredients: ['Premium MP Wheat Flour', 'A2 Desi Ghee (Makkhan-fed cows)', 'Organic Sulphurless Sugar', 'Real Cardamom Pod Powder', 'Grated dry Coconut'],
    shelfLife: '60 Days',
    nutrition: {
      calories: 465,
      protein: '5.8g',
      carbs: '62.0g',
      fat: '21.5g'
    },
    badges: ['A2 Desi Ghee', 'Handcrafted', 'Zero Preservatives', 'Rich & Flaky'],
    isBestSeller: true
  },
  {
    id: 'elaichi-thekua',
    name: 'Cardamom & Coconut Thekua',
    translationKey: 'elaichi_thekua',
    category: 'thekua',
    description: 'Crisp traditional cookies loaded with fresh hand-pounded green cardamom pods and crunchy dried coconut shreds for an exotic sweet flavor.',
    story: 'This variation is inspired by festive mornings under the neem tree, where cardamom pods would be cracked on large stone pestiles, filling the home with aroma.',
    price: 199,
    rating: 4.8,
    reviewCount: 156,
    unit: 'Pack of 350g',
    images: [
      'https://images.unsplash.com/photo-1605001011156-cbf0b0f67a51?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1600431521340-491eca880813?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80'
    ],
    ingredients: ['Sujata Whole Wheat Flour', 'Fine sugar syrup', 'Desi Ghee', 'Hand-pounded Elaichi pods', 'Dehydrated dry coconut chips'],
    shelfLife: '45 Days',
    nutrition: {
      calories: 430,
      protein: '6.1g',
      carbs: '65.2g',
      fat: '15.4g'
    },
    badges: ['Elaichi Fragrant', 'No Palm Oil', 'Stone-pressed', 'Fiber Rich'],
    inStock: false
  },
  {
    id: 'ajwain-nimki',
    name: 'Desi Ghee Ajwain Nimki',
    translationKey: 'ajwain_nimki',
    category: 'nimki',
    description: 'Crispy, crunchy diamond-cut savory snack richly seasoned with robust whole carom seeds (Ajwain) and sea salt. The perfect companion for hot Chai.',
    story: 'Every crunch carries the sharp notes of digestive ajwain, which is hand-roasted in low heat before being kneaded into flaky pastry sheets, folded perfectly 16 times.',
    price: 149,
    rating: 4.9,
    reviewCount: 289,
    unit: 'Pack of 250g',
    images: [
      'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80'
    ],
    ingredients: ['Sieved Heritage Wheat Flour', 'Cold-pressed Groundnut Oil for frying', 'Roasted Ajwain (Carom seeds)', 'Sendha Namak (Rock Salt)', 'Desi Ghee (Moyen)'],
    shelfLife: '90 Days (Keep in Airtight Container)',
    nutrition: {
      calories: 380,
      protein: '7.8g',
      carbs: '54.2g',
      fat: '14.8g'
    },
    badges: ['Very Crispy', '16-Fold Flakiness', 'Digestive Ajwain', 'Airtight Pack'],
    isBestSeller: true
  },
  {
    id: 'masala-nimki',
    name: '12-Spices Masala Nimki',
    translationKey: 'masala_nimki',
    category: 'nimki',
    description: 'Grandma’s secret 12-spice spice blend sprinkled onto layered savory ribbons. Highly addictive, savory, tangy, and deeply satisfying.',
    story: 'The masala mix uses Amchoor (sun-dried mango powder), stone-ground black pepper, roasted cumin, and black rock salt, blended by hand in stone mortars.',
    price: 159,
    rating: 4.7,
    reviewCount: 198,
    unit: 'Pack of 250g',
    images: [
      'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80'
    ],
    ingredients: ['Heritage Wheat Flour', 'Secret 12-Spice Powder (Black Pepper, Cumin, Amchoor, Asafetida, Ginger, Rock Salt, etc.)', 'Groundnut Oil', 'Desi Ghee (Moyen)'],
    shelfLife: '90 Days',
    nutrition: {
      calories: 395,
      protein: '7.5g',
      carbs: '52.0g',
      fat: '16.5g'
    },
    badges: ['Grandma’s Masala', 'Zero Preservatives', 'Tangy & Spicy', 'All Natural']
  },
  {
    id: 'spicy-nimki',
    name: 'Teekha Guntur Nimki',
    translationKey: 'spicy_nimki',
    category: 'nimki',
    description: 'For those who love a spicy kick! Seasoned with sun-dried Guntur red red-chili flakes and green chilies kneaded beautifully into the flaky wheat ribbons.',
    story: 'This Nimki pays homage to the vibrant heat of rural bazaars. The dough is infused with fresh paste of dark green chillies, offering a spicy burst in every bite.',
    price: 159,
    rating: 4.8,
    reviewCount: 124,
    unit: 'Pack of 250g',
    images: [
      'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=600&q=80'
    ],
    ingredients: ['Wheat Flour', 'Guntur Sun-dried Chili Flakes', 'Fresh Green Chili Paste', 'Cold-pressed Groundnut Oil', 'Desi Ghee', 'Handpicked Ajwain', 'Rock Salt'],
    shelfLife: '80 Days',
    nutrition: {
      calories: 405,
      protein: '7.2g',
      carbs: '53.1g',
      fat: '18.1g'
    },
    badges: ['Teekha Spicy', 'Infused Chilies', 'No Artificial Colors', 'Immunity Spices'],
    inStock: false
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    userName: 'Kalyani Mishra',
    rating: 5,
    date: 'June 02, 2026',
    comment: 'The Gur Thekua is absolute magic! It took me straight back to my childhood days in Darbhanga during Chhath Pooja. The fragrance of fennel seeds and the crunchiness of Desi Ghee are perfection. Thank you for this pure taste!',
    location: 'Patna, Bihar',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    verifiedPurchase: true
  },
  {
    id: 'rev-2',
    userName: 'Anand Shrivastava',
    rating: 5,
    date: 'May 28, 2026',
    comment: 'Unbelievably authentic Nimki! The ajwain notes are so fresh and the tea partner we were looking for. Hard to believe this is sold online and packaged so beautifully and hygienically. PAN India shipping was fast too.',
    location: 'New Delhi, NCR',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    verifiedPurchase: true
  },
  {
    id: 'rev-3',
    userName: 'Rekha Choudhary',
    rating: 5,
    date: 'June 05, 2026',
    comment: 'Desi Ghee Thekua has the perfect leaf design from the traditional sancha. My children love it. No refined white sugar makes it relatively guilt-free. Highly recommend for festive gifts!',
    location: 'Mumbai, Maharashtra',
    avatar: 'https://images.unsplash.com/photo-1594744803329-e58b31de215f?auto=format&fit=crop&w=150&q=80',
    verifiedPurchase: true
  },
  {
    id: 'rev-4',
    userName: 'Satish Pandey',
    rating: 5,
    date: 'June 10, 2026',
    comment: 'The 12-Spice Masala Nimki has an incredible tangy zing. It is incredibly crispy and standard of homemade quality. Packaging had a handwritten thank-you card. Superb startup brand!',
    location: 'Ranchi, Jharkhand',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    verifiedPurchase: true
  }
];

export const FAQS = [
  {
    question: 'How do you guarantee the traditional "Maa ke haath ka swad" taste?',
    answer: 'All our recipes are passed down through generations. We use authentic stone-pressed ingredients, handmade jaggery, pure cow Desi Ghee, and shape them using traditional wooden sanchas (carvers). We prepare snacks in small batches ensuring personal care and taste consistency, without any commercial chemical additives.'
  },
  {
    question: 'How long can I store the Thekua and Nimki?',
    answer: 'Our Thekua stays crisp and delicious for up to 45-60 days when kept in a dry container. The Nimki can be stored for up to 90 days. We pack everything in premium air-lock seals ensuring no atmospheric dampness affects the crispness.'
  },
  {
    question: 'Are there any hidden chemical preservatives or refined palm oil?',
    answer: 'Absolutely none! We pride ourselves on using 100% natural jaggery (Gur), whole wheat (Atta), pure cold-pressed groundnut oil, or rich A2 Desi Ghee. No palm oil, no artificial flavors, and no synthetic additives ever.'
  },
  {
    question: 'How fast do you ship and deliver across India?',
    answer: 'We prepare your snacks fresh to order within 24 hours of receiving it. Ground transit takes between 3 to 5 business days for pan-India delivery. You receive an active tracking URL immediately via SMS/Email.'
  },
  {
    question: 'Can I pay Cash on Delivery (COD)?',
    answer: 'Yes! COD is fully available throughout India for an extra charge of ₹20 to verify authentic delivery. You can also pay securely online using UPI, Cards, NetBanking, or Wallet options with free shipping over ₹499.'
  },
  {
    question: 'What is your refund policy if the pack is damaged?',
    answer: 'If there is any transit damage or breakage inside, we provide a 100% free immediate replacement or refund. Just reach out to us on WhatsApp/Email with dynamic pictures of the package.'
  }
];

export const INSTAGRAM_REELS = [
  {
    id: 'reef-1',
    title: 'Grinding fennel & blending golden jaggery on organic stone stone grinders.',
    videoThumbnail: 'https://images.unsplash.com/photo-1605001011156-cbf0b0f67a51?auto=format&fit=crop&w=300&q=80',
    likes: '12.4k',
    views: '115k',
    duration: '0:15',
    category: 'Ingedients Preparation'
  },
  {
    id: 'reef-2',
    title: 'Kneading fresh whole wheat flour with rich bubbling cows Desi Ghee.',
    videoThumbnail: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=300&q=80',
    likes: '8.9k',
    views: '92k',
    duration: '0:12',
    category: 'Handicraft Kneading'
  },
  {
    id: 'reef-3',
    title: 'Pressing dough pieces individually onto wooden sancha carvings for perfect leaf patterns.',
    videoThumbnail: 'https://images.unsplash.com/photo-1600431521340-491eca880813?auto=format&fit=crop&w=300&q=80',
    likes: '16.1k',
    views: '185k',
    duration: '0:18',
    category: 'Tracing the Sancha'
  },
  {
    id: 'reef-4',
    title: 'Slow-frying the flaky Nimki strips until perfectly crispy and golden-copper colored.',
    videoThumbnail: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=300&q=80',
    likes: '14.2k',
    views: '130k',
    duration: '0:14',
    category: 'Mouthwatering Fry'
  }
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    brand_name: 'Maati',
    tagline: 'Maa ke haath ka swad',
    hero_title: 'Traditional Pure Taste From Our Family Kitchen To Your Home',
    hero_sub: 'Crispy Sancha Thekuas kneaded with warm Desi Ghee & Jaggery, and multi-layered Ajwain Nimki. Preserving the pure soul of organic, village-style, slow-cooked snack craft.',
    cta_order: 'Order Fresh Today',
    cta_explore: 'Explore Snacks',
    badge_ghee: 'Deep Desi Ghee Moyen',
    badge_organic: 'Organic Sweeteners',
    badge_village: 'Village Recipe Heritage',
    trust_1: 'Homemade Heritage Love',
    trust_2: 'Zero Processed Preservatives',
    trust_3: 'Fresh To Order Preparation',
    trust_4: 'Strict Food Safety Standard',
    trust_5: 'PAN India Doorstep Shipping',
    section_products: 'Handmade Delicacies For You',
    section_products_sub: 'Slow roasted, beautifully pressed, and made in ultra-hygienic traditional village kitchens.',
    tab_all: 'All Delights',
    tab_thekua: 'Sweet Sancha Thekua',
    tab_nimki: 'Crispy Tangy Nimki',
    story_heading: 'Our Story: Roots of Nostalgia',
    story_p1: 'Growing up under the shade of massive mango trees in North India, the fragrance of jaggery melting on dry mud-stoves meant only one thing—Mothers kitchen was busy craft-making traditional snacks.',
    story_p2: 'At Maati, we wanted to revive that same emotional nostalgia. Every piece of Thekua we make is hand-pressed onto aged wooden moulds, leaving a leaf pattern that pays homage to Chhathi Maiya and age-old festive traditions.',
    story_p3: 'No machines, no steel rollers, no chemical extenders. Just pure whole wheat flour, locally-sourced jaggery, whole cardamom, and original A2 cow Desi Ghee prepared in modern stainless steel, highly hygienic village-center kitchens.',
    why_heading: 'Why Maati Snacks?',
    why_sub: 'Reclaiming the forgotten standard of real Indian wheat snacks, cooked safely with premium ingredients.',
    why_1_title: 'Stone-Milled Wheat',
    why_1_desc: 'We grind our Sehore wheat slowly in traditional stone mills to retain natural nutrition and crispy fibrous crunch.',
    why_2_title: 'Wood-Fired / Slow Heat',
    why_2_desc: 'Slow cooking on perfectly monitored flames produces a rich baking texture that commercial ovens simply cannot replicate.',
    why_3_title: 'A2 Cow Desi Ghee',
    why_3_desc: 'No palm oil or standard shortening. We use premium cow Desi Ghee to produce a melting crumb structure that is heart-friendly and extremely golden.',
    why_4_title: 'No Added Preservatives',
    why_4_desc: 'We vacuum seal all our orders immediately after packaging to preserve crispness naturally for 60+ days without any chemicals.',
    language_select: 'Language / भाषा',
    quick_view: 'Quick View',
    add_to_cart: 'Add to Cart',
    added: 'Added with Love!',
    back_to_shop: 'Back to Shop',
    ingredients_label: 'Authentic Ingredients',
    shelf_life_label: 'Shelf Life & Storage',
    nutrition_label: 'Nutritional Values (per 100g)',
    delivery_calc: 'Estimated Shipping Timing',
    reviews_heading: 'Blessed by 12,000+ Families',
    reviews_sub: 'Real stories of nostalgia, childhood festival emotions, and perfect evening tea times with Maati.',
    gallery_heading: 'Dadi Maa’s Digital Rasoi',
    gallery_sub: 'Sneak a peek into how we knead, mould, fry, and pack your favorite tea-time snacks. 100% transparent and hygienic.',
    cart_heading: 'Your Authentic Treat Basket',
    empty_cart: 'Your snack basket is empty. Maa’s recipes are waiting to be fresh baked for you!',
    subtotal: 'Snack Subtotal',
    shipping: 'Hygienic Secure Care Shipping',
    free: 'FREE (Order Above ₹499)',
    total: 'Total Amount',
    whatsapp_checkout: 'Fast Checkout via WhatsApp',
    cod_avail: 'COD Available (Pay Cash/UPI on Delivery)',
    order_success_title: 'Your Fresh Snack Batch is Kneaded!',
    order_success_sub: 'Thank you for supporting traditional village cooking. Dadi Maa is already starting on your batch!',
    chatbot_welcome: 'Namaste! I am Dadi Maa’s AI Rasoi Assistant. Ask me anything about our traditional recipes, shelf life, or jaggery sourcing!',
    checkout_title: 'Maa’s Kitchen Dispatch Details',
    gur_thekua_name: 'Gur & Saunf Thekua',
    gur_thekua_desc: 'An aromatic cookie made with premium whole wheat, organic desi jaggery, crushed fennel seeds, and baked slowly in wood-fired ovens.',
    gur_thekua_story: 'Prepared exactly as our Grandmothers made back in the village using hand-carved wooden moulds called "Sancha", leaving a beautiful leaf print.',
    desi_ghee_thekua_name: 'Sancha Desi Ghee Thekua',
    desi_ghee_thekua_desc: 'Rich, melt-in-mouth traditional biscuit rich in A2 Desi Ghee and sweetened with organic sulphurless sugar. Indulgent, authentic, and golden.',
    desi_ghee_thekua_story: 'Kneaded strictly by hand with generous dollops of warm Desi Ghee. The rich, buttery crackling texture is a heritage recipe preserved across five generations.',
    elaichi_thekua_name: 'Cardamom & Coconut Thekua',
    elaichi_thekua_desc: 'Crisp traditional cookies loaded with fresh hand-pounded green cardamom pods and crunchy dried coconut shreds for an exotic sweet flavor.',
    elaichi_thekua_story: 'This variation is inspired by festive mornings under the neem tree, where cardamom pods would be cracked on large stone pestiles, filling the home with aroma.',
    ajwain_nimki_name: 'Desi Ghee Ajwain Nimki',
    ajwain_nimki_desc: 'Crispy, crunchy diamond-cut savory snack richly seasoned with robust whole carom seeds (Ajwain) and sea salt. The perfect companion for hot Chai.',
    ajwain_nimki_story: 'Every crunch carries the sharp notes of digestive ajwain, which is hand-roasted in low heat before being kneaded into flaky pastry sheets, folded perfectly 16 times.',
    masala_nimki_name: '12-Spices Masala Nimki',
    masala_nimki_desc: 'Grandma’s secret 12-spice spice blend sprinkled onto layered savory ribbons. Highly addictive, savory, tangy, and deeply satisfying.',
    masala_nimki_story: 'The masala mix uses Amchoor (sun-dried mango powder), stone-ground black pepper, roasted cumin, and black rock salt, blended by hand in stone mortars.',
    spicy_nimki_name: 'Teekha Guntur Nimki',
    spicy_nimki_desc: 'For those who love a spicy kick! Seasoned with sun-dried Guntur red red-chili flakes and green chilies kneaded beautifully into the flaky wheat ribbons.',
    spicy_nimki_story: 'This Nimki pays homage to the vibrant heat of rural bazaars. The dough is infused with fresh paste of dark green chillies, offering a spicy burst in every bite.',
  },
  hi: {
    brand_name: 'माटी',
    tagline: 'माँ के हाथ का स्वाद',
    hero_title: 'हमारे पारिवारिक रसोईघर से आपके घर तक पारंपरिक शुद्ध स्वाद',
    hero_sub: 'शुद्ध देसी घी और जैविक गुड़ से सने सुनहरे सांचा ठेकुआ, और १६ परतों वाली एकदम कुरकुरी अजवाइन निमकी। गाँव की मिट्टी के चूलहे की खुशबू और शुद्धता अब आपके शहर में।',
    cta_order: 'आज ही ताज़ा आर्डर करें',
    cta_explore: 'स्नैक्स देखें',
    badge_ghee: 'शुद्ध देसी घी मोयन',
    badge_organic: 'जैविक गुड़ मिठास',
    badge_village: 'पारंपरिक गाँव की रेसिपी',
    trust_1: 'घर का प्यार व शुद्धता',
    trust_2: 'हानिकारक प्रिजर्वेटिव मुक्त',
    trust_3: 'ताज़ा आर्डर पर तैयारी',
    trust_4: 'स्वच्छता व सुरक्षा प्रमाणित',
    trust_5: 'पूरे भारत में सुरक्षित डिलीवरी',
    section_products: 'आपके लिए हमारे हस्तनिर्मित व्यंजन',
    section_products_sub: 'गाँव की महिलाओं द्वारा पारंपरिक चूल्हों के स्वाद और सुरक्षा मानदंडों के साथ तैयार किए गए स्नैक्स।',
    tab_all: 'सभी व्यंजन',
    tab_thekua: 'पारंपरिक मीठा ठेकुआ',
    tab_nimki: 'कुरकुरी चटपटी निमकी',
    story_heading: 'हमारी कहानी: गाँव की यादें',
    story_p1: 'गाँव में नीम और आम के पेड़ों की छांव में, मिट्टी के चूल्हे पर गुड़ की चाशनी उबलने की भीनी खुशबू से ही पता चल जाता था कि माँ का त्योहार वाला ठेकुआ पकने लगा है।',
    story_p2: 'माटी स्नैक्स के ज़रिए, हम उसी पुरानी सोंधी खुशबू और उत्सव के अहसास को आपके पास वापस लाना चाहते हैं। स्नैक्स का हर टुकड़ा लकड़ी के नक्काशीदार "सांचे" पर हाथ से दबाकर बनाया जाता है।',
    story_p3: 'कोई ऑटोमैटिक मशीन नहीं, कोई रिफाइंड पाम आयल नहीं। सिर्फ शुद्ध गेहूं का आटा, गाँव का गुड़, इलायची और असली दानेदार गाय का देसी घी, जो पूरी स्वच्छता और प्यार से पकाया जाता है।',
    why_heading: 'माटी स्नैक्स ही क्यों?',
    why_sub: 'मैदे और प्रिजर्वेटिव वाले पैकेटबंद स्नैक्स को छोड़ें, अपनाएं सेहतमंद और सोंधा पारंपरिक भारतीय स्वाद।',
    why_1_title: 'चक्की का पिसा आटा',
    why_1_desc: 'हम धीरे-धीरे चलने वाली पारंपरिक पत्थर की चक्की में पिसे गेहूं का उपयोग करते हैं ताकि पोषक तत्व बचे रहें।',
    why_2_title: 'लकड़ी की धीमी आंच',
    why_2_desc: 'पूरी निगरानी के साथ धीमी आंच पर पकाने से ठेकुआ अंदर से एकदम सोंधा और किनारों से कुरकुरा बनता है।',
    why_3_title: 'शुद्ध गाय का देसी घी',
    why_3_desc: 'हम रिफाइंड पाम ऑयल का उपयोग कभी नहीं करते। देसी घी का मोयन कचौड़ी जैसी परतदार खस्ता टेक्सचर देता है।',
    why_4_title: 'बिना केमिकल्स ६० दिन ताज़ा',
    why_4_desc: 'हम अपने स्नैक्स को तलने/बनाने के तुरंत बाद वैक्यूम सील कर देते हैं जिससे बिना किसी केमिकल के ६० दिनों तक यह ताज़ा और कुरकुरी रहती है।',
    language_select: 'भाषा बदलें',
    quick_view: 'झलक देखें',
    add_to_cart: 'टोकरी में डालें',
    added: 'टोकरी में जोड़ दिया गया है!',
    back_to_shop: 'वापस जाएँ',
    ingredients_label: 'शुद्ध सामग्री',
    shelf_life_label: 'रखरखाव और शेल्फ लाइफ',
    nutrition_label: 'पोषण मूल्य (प्रति १०० ग्राम)',
    delivery_calc: 'डिलीवरी का समय',
    reviews_heading: '१२,०००+ परिवारों की पसंद',
    reviews_sub: 'त्योहारों की यादें, बचपन का स्वाद और शाम की चाय का असली अहसास दिलाने वाले ग्राहकों के सच्चे अनुभव।',
    gallery_heading: 'दादी माँ की डिजिटल रसोई',
    gallery_sub: 'देखें कैसे तैयार होता है आपका पसंदीदा स्नैक। पूरी तरह पारदर्शी और स्वच्छ प्रक्रिया।',
    cart_heading: 'आपकी स्नैक टोकरी',
    empty_cart: 'आपकी टोकरी खाली है। माँ के हाथों के ताज़े स्वाद वाले स्नैक्स आपका इंतज़ार कर रहे हैं!',
    subtotal: 'स्नैक्स का मूल्य',
    shipping: 'सुरक्षित पैकेजिंग और डिलीवरी',
    free: 'मुफ़्त डिलीवरी (₹४९९ से ऊपर)',
    total: 'कुल राशि',
    whatsapp_checkout: 'व्हाट्सएप द्वारा फ़ास्ट आर्डर करें',
    cod_avail: 'नकद भुगतान (COD) उपलब्ध है',
    order_success_title: 'आपका ताज़ा स्नैक घान तैयार हो रहा है!',
    order_success_sub: 'पारंपरिक चूल्हे और महिलाओं के रोजगार का समर्थन करने के लिए धन्यवाद। दादी माँ ने तैयारी शुरू कर दी है!',
    chatbot_welcome: 'प्रणाम! हम दादी माँ के एआई रसोई सहायक बानी। हमरा से गुड़ की शुद्धता, ठेकुआ के शेल्फ लाइफ या डिलीवरी के बारे में कुछ भी पूछीं!',
    checkout_title: 'माँ की रसोई से भेजने का विवरण',
    gur_thekua_name: 'गुड़ और सौंफ ठेकुआ',
    gur_thekua_desc: 'प्रीमियम गेहूं के आटे, जैविक देसी गुड़, सौंफ की सौंधी खुशबू और मिट्टी के चूल्हे पर पके पारंपरिक मीठे सांचे वाले कुकीज़।',
    gur_thekua_story: 'यह बिल्कुल वैसे ही बनाया जाता है जैसे हमारी दादियां गाँव में बनाती थीं - लकड़ी के नक्काशीदार "सांचे" से सुंदर पत्ती के डिजाइन के साथ तैयार किया हुआ।',
    desi_ghee_thekua_name: 'सांचा देसी घी ठेकुआ',
    desi_ghee_thekua_desc: 'मुंह में घुलने वाला समृद्ध ए२ देसी घी से बना पारंपरिक ठेकुआ, जैविक चीनी से मीठा, गहरा सुनहरा और लजीज।',
    desi_ghee_thekua_story: 'दानेदार देसी घी की प्रचुर मात्रा के साथ पूरी तरह हाथ से गूंथा हुआ। पांच पीढ़ियों से संजोई गई यह विरासत वाली रेसिपी है।',
    elaichi_thekua_name: 'इलायची और नारियल ठेकुआ',
    elaichi_thekua_desc: 'हाथ से कुटी ताजी हरी इलायची और सूखे नारियल के लच्छों के स्वाद और भीनी खुशबू से भरपूर खस्ता मीठा ठेकुआ।',
    elaichi_thekua_story: 'यह रेसिपी नीम के पेड़ के नीचे त्योहारों की उन सुबहों से प्रेरित है जहां पत्थर की सिल-बट्टे पर इलायची कूटी जाती थी।',
    ajwain_nimki_name: 'देसी घी अजवाइन निमकी',
    ajwain_nimki_desc: 'कुरकुरी, परतदार डायमंड कटी हुई पारंपरिक निमकी, अजवाइन और समुद्री नमक के बेहतरीन संतुलित स्वाद के साथ। चाय का सच्चा साथी।',
    ajwain_nimki_story: 'हर टुकड़े में पाचक अजवाइन का तीखा स्वाद है, जिसे पूरी १६ परतों में गूंथकर एकदम खस्ता बनाया गया है।',
    masala_nimki_name: '१२-मसाला रिबन निमकी',
    masala_nimki_desc: 'दादी मां के सीक्रेट १२ मसालों के मिश्रण के चटपटे तीखे स्वाद वाली लच्छेदार खस्ता निमकी। बेहद स्वादिष्ट और कुरकुरी।',
    masala_nimki_story: 'इस मसाले में आमचूर, कुटी हुई काली मिर्च, भुना हुआ जीरा और काला नमक शामिल है जिसे हाथ से पीसा जाता है।',
    spicy_nimki_name: 'तीखा गुंटूर निमकी',
    spicy_nimki_desc: 'तीखे स्वाद के दीवानों के लिए! प्रसिद्ध गुंटूर सूखी लाल मिर्च के फ्लेक्स और ताजी हरी मिर्च के तीखेपन वाली खस्ता तीखी निमकी।',
    spicy_nimki_story: 'गाँव के हाट-बाजारों के तीखेपन को समर्पित। आटे में ताजी मिर्च का पेस्ट मिलाकर कुरकुरी पट्टियां तली जाती हैं।',
  },
  bho: {
    brand_name: 'माटी',
    tagline: 'मईया के हाथ के स्वाद',
    hero_title: 'हमरा गाँव-घर के पावन रसोई से रउआ दुआर तक असली सोंध स्वाद',
    hero_sub: 'देसी घी के खस्ता मोयन आ सोंध गुड़ से बनल सांचा ठेकुआ, आ १६ परतदार नमकीन निमकी। छठ मईया के महाप्रसाद जइसन सुगंध आ शुद्धता अब रउआ थाली में।',
    cta_order: 'आजुवे ताज़ा आर्डर करीं',
    cta_explore: 'स्नैक्स देखीं',
    badge_ghee: 'शुद्ध देसी घी के मोयन',
    badge_organic: 'गाँव के असली गुड़',
    badge_village: 'दादी-नानी के घरेलू रेसिपी',
    trust_1: 'हाथ के गढ़ल घर के प्यार',
    trust_2: 'कौनो Chemical प्रिजर्वेटिव ना',
    trust_3: 'आर्डर मिलला पर ताज़ा तैयारी',
    trust_4: 'एकदम साफ़-सुथरा ढंग से',
    trust_5: 'पूरा भारत में घर तक पहुँच',
    section_products: 'रउआ बदे खास हस्तनिर्मित व्यंजन',
    section_products_sub: 'गाँव के दीदी लोगन द्वारा काठ के सांचा पर गढ़ के बनावल शुद्ध आ लाजवाब स्नैक्स।',
    tab_all: 'सभ व्यंजन',
    tab_thekua: 'काठ के सांचा वाला ठेकुआ',
    tab_nimki: 'खस्ता नुनछुर निमकी',
    story_heading: 'हमार कहानी: माटी के सोंध सुगन्ध',
    story_p1: 'गाँव में जब मिट्टी के चूल्हा पर गोइठा के धीमी आंच पर गुड़ पघले, त पूरा टोला-मुहल्ला में इलायची आ सौंफ के महक पसर जाई। महक बता देवे की माई के रसोई चालू बा।',
    story_p2: 'माटी स्नैक्स के संगे, हमनी के ओह सोंध परम्परा आ बचपन के नेह-छोह के रउआ सोझा ले आईल चाहत बानी। हमनी के ठेकुआ आजुओ काठ के लकड़ी वाला सांचा पर हाथ से दबा के बनावल जाला।',
    story_p3: 'ना कवनो बड़ मशीन, ना कवनो नुकसानदेह डालडा। खाली सेहोर के गेहूं के आटा, गाँव के कोल्हू के गुड़, आ घर के बनल दानेदार देसी घी। स्वाद अइसन की सीधे बचपन के याद आ जाई।',
    why_heading: 'काहे चुनीं माटी स्नैक्स?',
    why_sub: 'रिफाइंड तेल आ मैदा के पैकेट छोड़ के, शुद्ध घी आ गेहूं से बनल सोंधा सेहतमंद नाश्ता अपनाईं।',
    why_1_title: 'हाथ-चक्की के गेहूं',
    why_1_desc: 'हमनी के गेहूं के धीरे-धीरे पारंपरिक जाता/चक्की पर पीसल जाला ताकि आटा के सोंधापन आ चोकर सुरक्षित रहे।',
    why_2_title: 'लकड़ी के धीमी आंच',
    why_2_desc: 'चूल्हा के धीमी मध्यम आंच पर तलला से ठेकुआ अन्दर ले एकदम खस्ता आ बहरी से कुरकुरा सुनहरा रंग के होला।',
    why_3_title: 'गाय के शुद्ध देसी घी',
    why_3_desc: 'पाम आयल के कभो प्रयोग ना होला। असली खस्ता मोयन बदे केवल शुद्ध दानेदार गाय के घी के इस्तेमाल कइल जाला।',
    why_4_title: 'बिना केमिकल ६० दिन ताज़ा',
    why_4_desc: 'घान तलाते ही हमनी के वैक्यूम पैक क देवेनी, जेसे बिना कवनो केमिकल के २ महीना ले स्नैक्स एकदम करारा आ ताज़ा रहेला।',
    language_select: 'भाषा चुनीं (बोली)',
    quick_view: 'निकट से देखीं',
    add_to_cart: 'टोकरी में रखीं',
    added: 'टोकरी में सहेजाइल गेल!',
    back_to_shop: 'दुकान पर चलीं',
    ingredients_label: 'असली शुद्ध सामग्री',
    shelf_life_label: 'सुरक्षित रखे के तरीका',
    nutrition_label: 'ताकत के मात्रा (प्रति १०० ग्राम)',
    delivery_calc: 'पहुँचे के समय',
    reviews_heading: '१२,०००+ परिवारों के आशीष',
    reviews_sub: 'रउआ जइसन भाई-बहिन आ माता जी लोग के प्यार आ सोंध गाँव के गोठ।',
    gallery_heading: 'दादी माई के डिजिटल रसोई',
    gallery_sub: 'देखीं कइसे आँखि के सोझा शुद्ध गेहूं, गुड़, घी आ इलायची से तैयार हो रहल बा रउआ सनेह क पोटली।',
    cart_heading: 'रउआ सनेह क टोकरी',
    empty_cart: 'टोकरी में कुछु नइखे! माई के हाथों के ताज़े ठेकुआ-निमकी रउआ रस्ता देखत बा।',
    subtotal: 'स्नैक्स के असली दाम',
    shipping: 'हवा-बंद सुरक्षित शिपिंग',
    free: 'मुफ़्त डिलीवरी (₹४९९ से ऊपर)',
    total: 'कुल दाम',
    whatsapp_checkout: 'व्हाट्सएप से झटपट आर्डर करीं',
    cod_avail: 'घर पहुँचे पर भुगतान क सुविधा (COD)',
    order_success_title: 'रउआ घान क कढ़ाई चढ़ गइल बा!',
    order_success_sub: 'गाँव के पारंपरिक दीदी लोगन के रोजगार देवे बदे धन्यवाद। दादी माई सनेह से घान तैयार करत बाड़ी!',
    chatbot_welcome: 'प्रणाम! हम दादी माई के एआई रसोई सहायक बानी। गुड़ के शुद्धता, ठेकुआ के शेल्फ लाइफ चाहे डिलीवरी के बारे में कुछुओ पूछीं, हम रउआ आपन भाषा भोजपुरी में बताइब!',
    checkout_title: 'माई के रसोई से दुआर तक क पता विवरण',
    gur_thekua_name: 'गुड़ सौंफ वाला ठकुआ',
    gur_thekua_desc: 'जांत पर पिसल गेहूं के आटा, गाँव के रसीला कोल्हू के गुड़ आ मोटी हरी सौंफ से सजल चूल्हा पर धीमे सिंकल मीठा ठकुआ।',
    gur_thekua_story: 'ई बिल्कुल उहे ठेकुआ ह जेके हमनी के दादी-नानी काठ के सांचा पर हाथ से गढ़ के बनाईं, जेपर पत्ता क पवित्र महक रहेला।',
    desi_ghee_thekua_name: 'गाय घी सांचा ठेकुआ',
    desi_ghee_thekua_desc: 'मुँह में जाते पघल जाय वाला पारम्परिक घी क ठेकुआ, जैविक चीनी के घोल से बान्हल आ गाय के पीला घी से डबडब खस्ता ठेकुआ।',
    desi_ghee_thekua_story: 'भोर ही हाथ से दबा के मथ मथ के घी के मोयन देके बनावल। इ पांच पीढ़ी से माई-बहिन लोगन के संजोवल पवित्र स्वाद ह।',
    elaichi_thekua_name: 'इलायची आ नारियल ठकुआ',
    elaichi_thekua_desc: 'सिल्लोट पर कुटल इलायची क सुगंध आ गरी गोला क दरदरा कतरन से सजावल कड़क मीठा ठकुआ।',
    elaichi_thekua_story: 'ई खास स्वाद नीम क छांह में छठ घाट पर माता जी लोगन क हाथ क कुटाई आ दुलार क याद दिलावेला।',
    ajwain_nimki_name: 'सोंध नुनछुर अजवाइन निमकी',
    ajwain_nimki_desc: 'कुरकुरी, परतदार तिकोन कटल पारम्परिक निमकी, अजवाइन आ सेंधा नमक क संतुलित सुगन्धित मेल। गरमा गरम चाय क संगी।',
    ajwain_nimki_story: 'अजवाइन के हाथ से भुजला के बाद चक्की क छनल आटा में सान के १६ बेर मोड़ क खस्ता पापड़ी नियन बनावल गेल बा।',
    masala_nimki_name: '१२-मसाला रिबन निमकी',
    masala_nimki_desc: 'दादी माई के १२ मसाला छिड़क के बनावल लच्छेदार करारी निमकी। जीभ चटकार कर देवे वाली सोंधापन।',
    masala_nimki_story: 'मसाला में अमचूर, खरल क मरीच, भुना जीरा आ काला नमक बा जेके जाता पर पीस के सहेजल जाला।',
    spicy_nimki_name: 'चटकार तीखा गुंटूर निमकी',
    spicy_nimki_desc: 'तीखा खोजी लोग खातिर विशेष! गुंटूर क लाल मिर्च आ हरी कुचलल मिर्च के देहात क मूंगफली तेल में छान के तैयार एकदम खस्ता निमकी।',
    spicy_nimki_story: 'गाँव क तीखा हाट क नेह सुगन्ध। पट्टियों में हरी मिर्च क रस डालके सान्कल आटे क कमाल ह ई।',
  }
};

export const getLocalizedIngredient = (ingredient: string, lang: Language): string => {
  const maps: Record<Language, Record<string, string>> = {
    en: {},
    hi: {
      'Sehore Whole Wheat Flour': 'सेहोर चोकरयुक्त गेहूं का आटा',
      'Organic sugarcane Jaggery (Gur)': 'जैविक गन्ने का कोल्हू गुड़',
      'Cold-pressed Mustard Oil': 'कच्ची घानी सरसों का तेल',
      'Green Fennel Seeds (Saunf)': 'मोटी हरी सौंफ',
      'Water': 'शुद्ध जल',
      'Premium MP Wheat Flour': 'प्रीमियम शरबती गेहूं का आटा',
      'A2 Desi Ghee (Makkhan-fed cows)': 'ए२ गाय का देसी घी',
      'Organic Sulphurless Sugar': 'जैविक सल्फर-रहित चीनी क खांड',
      'Real Cardamom Pod Powder': 'ताजी कुटी हरी इलायची',
      'Grated dry Coconut': 'कद्दूकस किया नारियल क लच्छे',
      'Sujata Whole Wheat Flour': 'सुजाता गेहूं का दरदरा आटा',
      'Fine sugar syrup': 'ठंडी चीनी क रसीली चाशनी',
      'Desi Ghee': 'शुद्ध गाय का देसी घी',
      'Hand-pounded Elaichi pods': 'हाथ से कुटी हरी इलायची',
      'Dehydrated dry coconut chips': 'सूखे नारियल क चिप्स',
      'Sieved Heritage Wheat Flour': 'पारंपरिक गेहूं का छना आटा',
      'Cold-pressed Groundnut Oil for frying': 'कच्ची घानी मूंगफली का तेल',
      'Roasted Ajwain (Carom seeds)': 'भुनी हुई हाजमा अजवाइन',
      'Sendha Namak (Rock Salt)': 'आर्गेनिक सेंधा या समुद्री नमक',
      'Desi Ghee (Moyen)': 'देसी घी का खस्ता मोयन',
      'Heritage Wheat Flour': 'पारंपरिक गेहूं का आटा',
      'Secret 12-Spice Powder (Black Pepper, Cumin, Amchoor, Asafetida, Ginger, Rock Salt, etc.)': 'दादी मां का गुप्त १२-मसालों का मिश्रण (काली मिर्च, जीरा, अमचूर, हींग, सौंठ आदि)',
      'Groundnut Oil': 'कच्ची घानी मूंगफली का तेल',
      'Wheat Flour': 'ताज़ा गेहूं का आटा',
      'Guntur Sun-dried Chili Flakes': 'गुंटूर कड़क लाल मिर्च के फ्लेक्स',
      'Fresh Green Chili Paste': 'ताजी हरी मिर्च का सोंधा पेस्ट',
      'Cold-pressed Groundnut Oil': 'कच्ची घानी मूंगफली तेल',
      'Handpicked Ajwain': 'हाथ से चुनी हुई अजवाइन',
      'Rock Salt': 'सेंधा नमक'
    },
    bho: {
      'Sehore Whole Wheat Flour': 'सेहोर क चोकरदार आटा',
      'Organic sugarcane Jaggery (Gur)': 'जैविक कोल्हू का लाल गुड़',
      'Cold-pressed Mustard Oil': 'घानी क कड़ू तेल',
      'Green Fennel Seeds (Saunf)': 'सुगन्धित मोटी सौंफ',
      'Water': 'साफ़ पानी',
      'Premium MP Wheat Flour': 'शरबती पिसा गेहूं आटा',
      'A2 Desi Ghee (Makkhan-fed cows)': 'पीला सुगन्धित देसी घी',
      'Organic Sulphurless Sugar': 'जैविक चीनी क बूरा',
      'Real Cardamom Pod Powder': 'खरल क कुटल इलायची',
      'Grated dry Coconut': 'कद्दूकस नारियल',
      'Sujata Whole Wheat Flour': 'सुजाता गेहूं क आटा',
      'Fine sugar syrup': 'चीनी क रसीला घोल',
      'Desi Ghee': 'गाय क देसी घी',
      'Hand-pounded Elaichi pods': 'हाथ क कुटल इलायची',
      'Dehydrated dry coconut chips': 'नारियल क चिप्स',
      'Sieved Heritage Wheat Flour': 'गेहूं क छनल आटा',
      'Cold-pressed Groundnut Oil for frying': 'घानी क बादाम तेल',
      'Roasted Ajwain (Carom seeds)': 'भुजल हाजमा अजवाइन',
      'Sendha Namak (Rock Salt)': 'सेंधा नमक',
      'Desi Ghee (Moyen)': 'गाय घी क खस्ता मोयन',
      'Heritage Wheat Flour': 'गेहूं क आटा',
      'Secret 12-Spice Powder (Black Pepper, Cumin, Amchoor, Asafetida, Ginger, Rock Salt, etc.)': 'दादी माई क गुप्त १२-मसालों क मिश्रण (मरीच, जीरा, अमचूर, हींग, सोंठ)',
      'Groundnut Oil': 'मूंगफली क तेल',
      'Wheat Flour': 'गेहूं क आटा',
      'Guntur Sun-dried Chili Flakes': 'गुंटूर क लाल मिर्च',
      'Fresh Green Chili Paste': 'हरी मिर्च क पेस्ट',
      'Cold-pressed Groundnut Oil': 'मूंगफली तेल',
      'Handpicked Ajwain': 'चुनल अजवाइन',
      'Rock Salt': 'सेंधा नून'
    }
  };
  return maps[lang]?.[ingredient] || ingredient;
};

export const getLocalizedShelfLife = (shelfLife: string, lang: Language): string => {
  const maps: Record<Language, Record<string, string>> = {
    en: {},
    hi: {
      '45 Days (Store in cool, dry container)': '४५ दिन (हवाबंद डिब्बे में रखें)',
      '60 Days': '६० दिन (ताज़गी बनी रहेगी)',
      '45 Days': '४५ दिन',
      '90 Days (Keep in Airtight Container)': '९० दिन (हवाबंद डिब्बे में रखें)',
      '90 Days': '९० दिन',
      '80 Days': '८० दिन'
    },
    bho: {
      '45 Days (Store in cool, dry container)': '४५ दिन (सलीकेदार हवाबंद डिब्बा)',
      '60 Days': '६० दिन ले एकदम ताज़ा',
      '45 Days': '४५ दिन',
      '90 Days (Keep in Airtight Container)': '९० दिन ले एकदम कड़क',
      '90 Days': '९० दिन',
      '80 Days': '८० दिन'
    }
  };
  return maps[lang]?.[shelfLife] || shelfLife;
};

export const getLocalizedBadge = (badge: string, lang: Language): string => {
  const maps: Record<Language, Record<string, string>> = {
    en: {},
    hi: {
      'Pure Jaggery': 'शुद्ध गुड़',
      'Wooden Sancha': 'लकड़ी का सांचा',
      'Chhath Special Recipe': 'छठ पूजा विशेष विधि',
      'Soft Crunchy': 'खस्ता और कुरकुरा',
      'A2 Desi Ghee': 'ए२ देसी घी',
      'Handcrafted': 'हाथ से बना',
      'Zero Preservatives': 'हानिकारक केमिकल मुक्त',
      'Rich & Flaky': 'दानेदार व परतदार',
      'Elaichi Fragrant': 'इलायची खुशबू',
      'No Palm Oil': 'पाम आयल मुक्त',
      'Stone-pressed': 'सिल-बट्टा कुटी',
      'Fiber Rich': 'फाइबर युक्त सेहतमंद',
      'Very Crispy': 'बेहद खस्ता',
      '16-Fold Flakiness': '१६ परतदार खस्ता',
      'Digestive Ajwain': 'पाचक अजवाइन',
      'Airtight Pack': 'हवाबंद पैकेजिंग',
      'Grandma’s Masala': 'दादी का मसाला',
      'Tangy & Spicy': 'चटपटा व तीखा',
      'All Natural': '१००% प्राकृतिक',
      'Teekha Spicy': 'चटपटा तीखा घान',
      'Infused Chilies': 'सूखी मिर्च फ्लेक्स',
      'No Artificial Colors': 'कृत्रिम रंग मुक्त',
      'Immunity Spices': 'गुणकारी मसाले'
    },
    bho: {
      'Pure Jaggery': 'शुद्ध गुड़',
      'Wooden Sancha': 'काठ के सांचा',
      'Chhath Special Recipe': 'छठ मइया प्रसाद विधि',
      'Soft Crunchy': 'खस्ता आ कुरकुरा',
      'A2 Desi Ghee': 'ए२ देसी घी',
      'Handcrafted': 'हाथ के गढ़ल',
      'Zero Preservatives': 'कौनों प्रिजर्वेटिव ना',
      'Rich & Flaky': 'दानेदार व कड़क',
      'Elaichi Fragrant': 'इलायची सुगन्ध',
      'No Palm Oil': 'पाम आयल ना',
      'Stone-pressed': 'सिलौट पर पीसल',
      'Fiber Rich': 'ताकत से भरपूर',
      'Very Crispy': 'एकदम कुरकुरा',
      '16-Fold Flakiness': '१६ परतदार खस्ता',
      'Digestive Ajwain': 'हाजमा अजवाइन',
      'Airtight Pack': 'सलीकेदार डिब्बा',
      'Grandma’s Masala': 'दादी मां के मसाला',
      'Tangy & Spicy': 'नुनछुर आ चटकार',
      'All Natural': '१००% प्राकृतिक सुगन्ध',
      'Teekha Spicy': 'तीखा चटकार घान',
      'Infused Chilies': 'मिर्च क फ्लेक्स',
      'No Artificial Colors': 'कौनों रंग ना',
      'Immunity Spices': 'हल्दी-मरीच गुण'
    }
  };
  return maps[lang]?.[badge] || badge;
};
